#!/bin/bash
#SBATCH -J hybrid_test
#SBATCH -o hybrid_test.out
#SBATCH -e hybrid_test.err
#SBATCH -p shared
#SBATCH -n 2
#SBATCH -c 4
#SBATCH -t 180
#SBATCH --mem-per-cpu=4000
export OMP_NUM_THREADS=4
srun -n 2 --cpus-per-task=4 --mpi=pmix ./hybrid_test.x
